spring.application.name=Engineering Data Quality Analyzer
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

spring.datasource.url=jdbc:postgresql://localhost:5432/dataqualitydb
spring.datasource.username=postgres
spring.datasource.password=Sathvika@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# this is to debug and find the exact error
#spring.web.error.include-message=always
#logging.level.org.springframework.web=DEBUG